spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restoran
    username: postgres
    password: baiel123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
      multipart:
        enabled: true
  jwt:
    secret_key: baielkarybaevspringkey

spring.data.rest:
  default-page-size: 20
  base-path: /api
  detection-strategy: annotated


server:
  port: 8082



